### ISSUE TITLE
MVCアーキテクチャに沿うようにディレクトリを整理

### ISSUE THREAD

**Issue by yamataku29** [sagaraEito/Every-Memo#8]
## 概要
現状のソースコードの状態だと全てのファイルが`SimpleMemoApp`ディレクトリ直下に配置されてしまっているため、少なくとも`Model`/`View`/`Controller`のフォルダを作成してそれぞれのディレクトリに適したファイルを格納するようにしましょう。

**Comment by sagaraEito** [comment]
質問です❗️
以下のように一応フォルダ分けをしていると思うのですが…
理解力が不足していてすみません。
もう一つ上の階層にてMVC分けを行うということでしょうか❓
<img width="332" alt="スクリーンショット 2021-04-12 4 31 53" src="https://user-images.githubusercontent.com/69618315/114318475-14921280-9b48-11eb-97dd-b8df00e87ed9.png">

**Comment by yamataku29** [comment]
おっと、なるほど。
今最新の状態は`develop`ブランチなのですね😅

`main`ブランチに対してレビューをしていました😵
