### ISSUE TITLE
継承をしないクラスにはfinal修飾子を付与する

### ISSUE THREAD

**Issue by yamataku29** [sagaraEito/Every-Memo#9]
## 概要
継承をする予定のないクラスには`final`修飾子を付与しましょう。
これを付与することによって、「当該クラスは他のクラスに継承されない」ことを明示できるため、そのクラス内のロジックを変更する際に改修範囲を限定的にすることができます。

**Comment by sagaraEito** [comment]
質問です❗️
final修飾子はすでに振ってあると思うのですが…❓
マージがうまく反映されていないのでしょうか…❓

**Comment by yamataku29** [comment]
https://github.com/sagaraEito/SimpleMemo/issues/8#issuecomment-817393432

> おっと、なるほど。
今最新の状態はdevelopブランチなのですね😅
> 
> mainブランチに対してレビューをしていました😵

こちらも同様に`main`ブランチを見ていたのが原因ですね、、、

**Comment by sagaraEito** [comment]
あれ、pullRequestでmainブランチにも反映したと思うのですが…
まだgitの使い方に慣れていないようです😭
お手数をおかけしてしまい申し訳ありません🙇‍♀️🙇‍♂️

**Comment by sagaraEito** [comment]
度々すみません🙇‍♀️
#6 と #7 のプルリクでfinal修飾子とprivateの追加をdevelopブランチからmainブランチにマージしたと思うのですが、もしかしてそこがうまくいっていないのでしょうか❓

**Comment by yamataku29** [comment]
今確認をしたところ、`main`ブランチ上でもfinal修飾子が付与されていることを確認しました👌
おそらくマージ前に確認したことが原因ですね🤔

**Comment by sagaraEito** [comment]
さっき、#12 にてマージを実行したからmainにも反映されたということでしょうか❓
それともヤマタクさんがチェックしていたのはアプリが出来上がったときにクローンされたフォルダだったということでしょうか❓
また、お手数ですがprivateとfinal修飾子、またMVCの分け方について改めてレビューをいただけると幸いです☺️

**Comment by yamataku29** [comment]
> さっき、#12 にてマージを実行したからmainにも反映されたということでしょうか❓

そういうことですね👌

> それともヤマタクさんがチェックしていたのはアプリが出来上がったときにクローンされたフォルダだったということでしょうか❓

出来上がった時かどうかは分からないですが、少なくとも僕がローカルにcloneした地点ではマージされていなかったというお事ですね😌

> また、お手数ですがprivateとfinal修飾子、またMVCの分け方について改めてレビューをいただけると幸いです☺️

了解です👌
こちらは後ほど対応しますね。

**Comment by sagaraEito** [comment]
なるほど❗️
ありがとうございます😊
ではよろしくお願いします❗️
また、新しく"[コードレビュー]ヤマタクさん"というMilestoneを作成しましたので新規にIssueを作成する際は振っていただけると幸いです☺️
